### ISSUE TITLE
${spring.cloud.client.ip-address} ignore spring.cloud.inetutils.preferred-networks

### ISSUE THREAD

**Issue by cooperlyt** [spring-cloud/spring-cloud-commons#1218] opened 2023-03-16 03:03 UTC
**Describe the bug**
Environment:

Spring boot:3.0.4
Spring cloud:2022.0.1 

spring-cloud-commons: 4.0.1
OpenJdk： 17

When preferredNetworks are configured in a multi-network interface card environment, ${spring.cloud.client.ip-address} return a wrong IP.
`application.yml`
```yml
spring:
  cloud:
    inetutils:
      use-only-site-local-interfaces: false
      preferred-networks:
        - 172.16.
```

Look like a configured loading error. I trace the source code.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/4219608/225498196-b68a9bb4-c4de-4fc2-87e3-7b6c9b7847c3.png">

preferredNetworks list is always empty!

**Sample**

set `spring.cloud.inetutils.preferred-networks` is `172.16.` in `application.yml`,test fail!
```java
@Slf4j
@ExtendWith(SpringExtension.class)
@SpringBootTest
public class IpTest {

  @Autowired
  private InetUtils inetUtils;

  @Value("${spring.cloud.client.ip-address}")
  private String ip;

  @Autowired
  private InetUtilsProperties properties;

//fail
  @Test
  public void testEnvironmentIP(){
    String regex = "172.16.";
    assertTrue(ip == null || "127.0.0.1".equals(ip) ||  ip.matches(regex) || ip.startsWith(regex));
  }

//pass
  @Test
  public void testFirstNonLoopbackAddress(){
    String regex = "172.16.";
    InetAddress hostAddress = inetUtils.findFirstNonLoopbackAddress();
    assertTrue(hostAddress == null || "127.0.0.1".equals(hostAddress.getHostAddress()) || hostAddress.getHostAddress().matches(regex) || hostAddress.getHostAddress().startsWith(regex));
  }


 //pass
  @Test
  public void testProperties(){
    String regex = "172.16.";

    assertFalse(properties.isUseOnlySiteLocalInterfaces());  //pass
    assertTrue(properties.getPreferredNetworks().contains(regex)); //pass

    InetAddress hostAddress = new InetUtils(properties).findFirstNonLoopbackAddress();
    assertTrue(hostAddress == null || "127.0.0.1".equals(hostAddress.getHostAddress()) || hostAddress.getHostAddress().matches(regex) || hostAddress.getHostAddress().startsWith(regex));
  }

}
```

**Comment by cooperlyt** [comment] 2023-03-18 00:21
oh!  if I want used preferred-networks, then use-only-site-local-interfaces must be false!

**Comment by cooperlyt** [comment] 2023-03-18 00:33
${spring.cloud.client.ip-address} still ignore preferred-networks

**Comment by OlgaMaciaszek** [comment] 2024-06-25 11:36
Hello, @cooperlyt, thanks for reporting the issue. This should have been fixed with https://github.com/spring-cloud/spring-cloud-commons/commit/b1e8d6a08c920a6b263d0effc993f7cf07207318. `2022.0.x` is no longer in OSS support. Please try on the current version (`2023.0.2`). If the issue persists, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue as a link to a sample GitHub repo with an executable project/ tests rather than pasted in code.

**Comment by spring-cloud-issues** [comment] 2024-07-02 11:40
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-07-09 11:40
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-07-09 11:40 UTC
Labels: feedback-reminder
