### ISSUE TITLE
Two different properties for disabling Discovery or Auto registration

### ISSUE THREAD

**Issue by shivamgoel** [spring-cloud/spring-cloud-commons#217] opened 2017-06-01 00:59 UTC
Hi,

Came across below two properties , which achieve the same behavior that is not auto registering when starting up. I am using 1.3.0 release
 
Available in [CommonsClientAutoConfiguration](https://github.com/spring-cloud/spring-cloud-commons/blob/f60dbeb5e6265b04604bd7774e06678769df67ba/spring-cloud-commons/src/main/java/org/springframework/cloud/client/CommonsClientAutoConfiguration.java) class
spring.cloud.discovery.enabled=false

Available in the official documentation and also suggested in closed [Issue](https://github.com/spring-cloud/spring-cloud-commons/issues/196) #(196)
spring.cloud.service-registry.auto-registration.enabled=true

Tried following combinations

1. using any one of the above properties  as false does not registers my application
2. Below does not register
spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=true
3. Below also does not register
spring.cloud.discovery.enabled=true
spring.cloud.service-registry.auto-registration.enabled=false
4. using any one of the above properties  as true does registers my application

So, I want to understand the reason behind two different properties achieving same behavior, if this is NOT a bug. Eventually I want to gain enough reasoning to suggest one over another to be used as a best practice. As of now we are planning to use netflix eureka for discovery but if one of the property is more generic which can support swapping the underlying service registry than I will prefer that.

**Comment by spencergibb** [comment] 2017-06-01 18:57
Previously, discovery did auto-registration. Now it has been separated to another package. Disabling  discovery should not disable auto-registration though.

**Comment by shivamgoel** [comment] 2017-06-01 19:34
Verified again, below combination does NOT register the service with eureka server

spring.cloud.discovery.enabled=false
spring.cloud.service-registry.auto-registration.enabled=true

PS : I am using @EnableEurekaClient annotation, if that should make a difference

**Comment by shivamgoel** [comment] 2017-06-15 22:26
so does this behaviour qualify to be a bug ?

**Comment by spencergibb** [comment] 2017-06-16 20:17
yes

**Comment by jigarashah** [comment] 2018-05-21 18:55
Not sure if same issue 

I have below config. it still tries to register.
```

server:
  port: 10012
spring:
  profiles: dev
  cloud:
    config:
      enabled: false
    discovery:
      enabled: false
    service-registry:
      auto-registration:
        enabled: false

```


```
com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused: connect
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:187) ~[jersey-apache-client4-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.filter.GZIPContentEncodingFilter.handle(GZIPContentEncodingFilter.java:123) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.netflix.discovery.EurekaIdentityHeaderFilter.handle(EurekaIdentityHeaderFilter.java:27) ~[eureka-client-1.8.8.jar:1.8.8]
	at com.sun.jersey.api.client.Client.handle(Client.java:652) ~[jersey-client-1.19.1.jar:1.19.1]
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:682) ~[jersey-client-1.19.1.jar:1.19.1]
```

**Comment by ryanjbaxter** [comment] 2018-06-04 14:36
This works for me in Edgware and Finchley.  I suggest users experiencing this problem upgrade to the latest release.

**Comment by ryanjbaxter** [comment] 2018-06-21 16:44
Closing, please reopen if someone can provide a sample that reproduces.

**Closed by ryanjbaxter** 2018-06-21 16:44 UTC

**Comment by ryanjbaxter** [comment] 2018-10-31 14:08
I dont see why all this is necessary, cant you just set these properties in your configuration properties under a profile?

**Comment by alexmarques** [comment] 2018-10-31 14:50
yes I can, the odd thing is when I configure the spring-webmvc only with @EnableEurekaClient annotation, it works just fine, but in spring-webflux the application tries to register itself to an eureka server even though I am disabling it in the local dev.

**Comment by alexmarques** [comment] 2018-10-31 17:08
@ryanjbaxter I did what you suggested, I create the file application-local.yml
```yml
spring:
  application:
    name: app

eureka:
  client:
    enabled: false
```

it did work as expected, but I was looking for disabling it programatically, which does not work.

but I think it shoud work both ways, programatically and via properties file.

**Comment by dvsingh9** [comment] 2019-08-30 12:28
> @ryanjbaxter I did what you suggested, I create the file application-local.yml
> 
> ```yaml
> spring:
>   application:
>     name: app
> 
> eureka:
>   client:
>     enabled: false
> ```
> 
> it did work as expected, but I was looking for disabling it programmatically, which does not work.
> 
> the point is, it should work both ways, programmatically and via the properties file.

That works for me also.
