### ISSUE TITLE
Maven Dependency spring-cloud-config-client causes issues with spring-boot-autoconfigure in Cloud Foundry

### ISSUE THREAD

**Issue by Huo12345** [spring-cloud/spring-cloud-commons#443] opened 2018-10-10 07:46 UTC
# Summary
I was trying to get a spring-cloud-configuration-server running in our cloud environment. When extending an existing component with the maven dependency spring-cloud-configuration-client to make it consume the configuration from the configuration server, the application startup failed with the following error:

```
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT ***************************
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT APPLICATION FAILED TO START
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT ***************************
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Description:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Reason: Failed to determine a suitable driver class
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Action:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Consider the following:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT     If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT     If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
   2018-10-10T09:28:51.91+0200 [APP/PROC/WEB/0] OUT Exit status 1
```

I've created the minimal application to reproduce the error. See steps below.

# Steps to reproduce
## Step 1
Create a minimal spring-boot application using a database:
pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>spring-config-demo</artifactId>
    <version>1.0-SNAPSHOT</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.5.RELEASE</version>
    </parent>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
        </dependency>

    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```

DemoApplication.java
```
package com.example.spring_config_demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }
}
```

DemoController.java
```
package com.example.spring_config_demo;

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


@RestController
@RequestMapping("/")
public class DemoController {

    @RequestMapping(method = RequestMethod.GET)
    public String helloWorld() {
        return "Hello World";
    }
}
```

## Step 2
Build and deploy application to your cloud foundry environment. Create a MariaDB service and bind it to the application. Restart the application and check if the logs are fine.

## Step 3
Add the dependency spring-cloud-configuration-client to the pom.xml, build and deploy the application

Dependency:
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-config-client</artifactId>
    <version>2.0.1.RELEASE</version>
</dependency>
```

# Expected result
The application should start up without any change in behavior.

# Actual result
The startup of the application fails with the following message:
```
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT 2018-10-10 07:28:51.827 ERROR 8 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT ***************************
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT APPLICATION FAILED TO START
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT ***************************
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Description:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Reason: Failed to determine a suitable driver class
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Action:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT Consider the following:
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT     If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
   2018-10-10T09:28:51.82+0200 [APP/PROC/WEB/0] OUT     If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
   2018-10-10T09:28:51.91+0200 [APP/PROC/WEB/0] OUT Exit status 1
```

# Actions taken

- Aligned the versions of the dependencies (using spring-boot-starter-parent version 2.0.1.RELEASE)
- Rebinding the service
- Setting the driver with the property `spring.datasource.driver-class-name`

# Additional Information
- I attached the full log of the failed application startup [startup.log](https://github.com/spring-cloud/spring-cloud-config/files/2463635/startup.log)
- As far as I can tell we are using cloud foundry with these versions: Portal 4.10.6 - EXT API 4.10.1 - CF API 2.121.0
- MariaDB version: 10.1.22

**Comment by ryanjbaxter** [comment] 2018-12-18 15:02
@Huo12345 can you update us on whether this is still effecting you?

**Comment by Huo12345** [comment] 2018-12-19 08:12
Currently we have no impact, but we are planning to put a microservice using a DB and the cloud config server life towards the end of Q1 2019. Then this will affect us.

**Comment by ryanjbaxter** [comment] 2018-12-19 15:14
I still am having a hard time reproducing the problem locally.  Everything seems to work fine for me when I have mariadb running locally and running your sample.  I am not sure exactly how to figure out the right solution without a way to reproduce this.

**Comment by spencergibb** [comment] 2018-12-19 15:22
Maybe there's a way to run with the Java build pack code locally, @nebhale?

**Comment by nebhale** [comment] 2018-12-19 18:36
Yep, [you absolutely can](https://github.com/cloudfoundry/java-buildpack/blob/master/docs/debugging-the-buildpack.md#running-the-buildpack-locally).

**Comment by ryanjbaxter** [comment] 2018-12-20 18:06
Thanks @nebhale!  

@Huo12345 can you give us a sample the reproduces the problem when running the buildpack locally?

**Comment by Huo12345** [comment] 2018-12-20 22:20
Will do after christmas holidays.

**Comment by nebhale** [comment] 2019-01-07 16:54
Yes, the buildpack only runs on a certain set of supported platforms.  So you'll need to be on a late-ish version of Ubuntu (`trusty` or `bionic`) or macOS.  The code for dealing with RHEL is a relic of when we did actually support it, but that hasn't been for four years or so.

**Comment by spring-issuemaster** [comment] 2019-01-29 15:23
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-07 21:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-14 21:11
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by spencergibb** [comment] 2019-02-14 21:13
Ping @Huo12345

**Comment by Huo12345** [comment] 2019-02-15 12:30
Had some issues running the build pack locally but managed to do it now with cflocal. I’ll need to run some more tests to make sure I have the same behavior. Should be by Monday.

**Comment by spring-issuemaster** [comment] 2019-02-22 12:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-03-01 12:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2019-03-01 12:37 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by FSDPOC** [comment] 2021-01-20 02:52
Try to add this dependency
<dependency>
   <groupId>org.springframework.cloud</groupId>
   <artifactId>spring-cloud-starter-bootstrap</artifactId>
</dependency>

**Comment by spencergibb** [comment] 2021-01-20 03:01
This problem existed long before that starter did, so it is not a solution
