### ISSUE TITLE
Custom @Qualifier on dependency of a @RefreshScope @Component not working after scope is refreshed

### ISSUE THREAD

**Issue by sarah-micallef** [spring-cloud/spring-cloud-commons#651] opened 2019-12-09 14:42 UTC
spring-cloud version: Greenwich.SR2

I have a custom qualifier, such as the following:

```java
    @Qualifier
    @Retention(RetentionPolicy.RUNTIME)
    @Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.METHOD, ElementType.TYPE})
    public @interface SomeBean {}
```
which is used to qualify one of beans of type `DummyDependency` as follows:
```java
@Configuration
public class ApplicationConfiguration {
    
    @Bean
    @SomeBean 
    public DummyDependency dummyDependency1() {
        return new DummyDependency();
    }
}
```
and also to qualify the `DummyDependency` dependency injected using the constructor of some other bean as follows:

```java
@Component
@RefreshScope
public class BeanWithRefreshScope {
    private final DummyDependency dummyDependency;

    @Autowired
    public BeanWithRefreshScope(@SomeBean final DummyDependency dummyDependency) {
        this.dummyDependency = dummyDependency;   
    }
}
```

I have multiple `DummyDependency` beans annotated with different qualifiers declared as beans in a `@Configuration` class similar to `dummyDependency`(). The application starts up successfully. But, whenever the scope of the application is refreshed and a request is made to `BeanWithRefreshScope`, then a `NoUniqueBeanDefinitionException` is thrown stating that a single bean is expected but X found.

I expect the custom `@Qualifier` to still be taken into account when the scope is refreshed.

**Comment by ryanjbaxter** [comment] 2019-12-09 15:08
Can you please try and reproduce this with Greenwich.SR4 and/or Hoxton.RELEASE?

**Comment by sarah-micallef** [comment] 2019-12-10 07:21
Problem still persists with 
* spring-cloud Greenwich.SR4 and spring-boot 2.1.7.RELEASE 
* spring-cloud Haxton.RELEASE and spring-boot 2.2.2.RELEASE

**Comment by OLPMO** [comment] 2020-01-10 13:01
I am interested in this issue,could you provide a minimal demo that  can reproduce the problem?@sarah-micallef

**Comment by spencergibb** [comment] 2020-01-14 19:30
I'm unable to recreate the problem using the snippets above.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-issuemaster** [comment] 2020-01-21 19:34
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-01-28 19:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-01-28 19:31 UTC
Labels: feedback-reminder, waiting for feedback
