### ISSUE TITLE
Multi-context spring-cloud  repetition LoadBalancerInterceptor

### ISSUE THREAD

**Issue by zhangle910522** [spring-cloud/spring-cloud-commons#1166] opened 2022-11-02 08:30 UTC
**Describe the bug**

I use spring-boot-starter-parent version 2.7.2，spring-cloud version 2021.0.2

publish multiple Dispatcher load  SubApplicationContext。

@Primary
    @Bean
    public DispatcherServletRegistrationBean dispatcherServletRegistrationBeanRest2() {
        String serviceName = "service2";

        AnnotationConfigServletWebApplicationContext subApplicationContext = new AnnotationConfigServletWebApplicationContext();
        subApplicationContext.setParent(applicationContext);

        subApplicationContext.setId(serviceName);

        subApplicationContext.register(Service2Configuration.class);

        DispatcherServlet dispatcherServlet = new DispatcherServlet(subApplicationContext);
        DispatcherServletRegistrationBean dispatcher = new DispatcherServletRegistrationBean(dispatcherServlet , "/"+serviceName+"/*");
        dispatcher.setName(serviceName);
        dispatcher.setLoadOnStartup(1);
        dispatcher.setOrder(Ordered.HIGHEST_PRECEDENCE);

        methodInvokeService.putApplicationContext(serviceName,subApplicationContext);
        return dispatcher;
    }

Use  @LoadBalanced

    @LoadBalanced
    @Bean("mergeRouteRestTemplate")
    public RestTemplate mergeRouteRestTemplate() {
    }

restTemplate. post("http://multiple-base/service1/api/user/get");   throw Exception：

Exception：
```
java.lang.IllegalStateException: No instances available for 192.168.4.83
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:89) ~[spring-cloud-loadbalancer-3.1.2.jar:3.1.2]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor.intercept(LoadBalancerInterceptor.java:56) ~[spring-cloud-commons-3.1.2.jar:3.1.2]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.3.22.jar:5.3.22]
	at org.springframework.cloud.client.loadbalancer.BlockingLoadBalancerRequest.apply(BlockingLoadBalancerRequest.java:55) ~[spring-cloud-commons-3.1.2.jar:3.1.2]
	at org.springframework.cloud.client.loadbalancer.BlockingLoadBalancerRequest.apply(BlockingLoadBalancerRequest.java:32) ~[spring-cloud-commons-3.1.2.jar:3.1.2]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerRequestAdapter.apply(LoadBalancerRequestAdapter.java:43) ~[spring-cloud-commons-3.1.2.jar:3.1.2]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:114) ~[spring-cloud-loadbalancer-3.1.2.jar:3.1.2]
	at org.springframework.cloud.loadbalancer.blocking.client.BlockingLoadBalancerClient.execute(BlockingLoadBalancerClient.java:91) ~[spring-cloud-loadbalancer-3.1.2.jar:3.1.2]
	at org.springframework.cloud.client.loadbalancer.LoadBalancerInterceptor.intercept(LoadBalancerInterceptor.java:56) ~[spring-cloud-commons-3.1.2.jar:3.1.2]
	at org.springframework.http.client.InterceptingClientHttpRequest$InterceptingRequestExecution.execute(InterceptingClientHttpRequest.java:93) ~[spring-web-5.3.22.jar:5.3.22]
```

cause： restTemplate have two LoadBalancerInterceptor
LoadBalancerAutoConfiguration invoke twice code：
```
@Bean
@ConditionalOnMissingBean
public RestTemplateCustomizer restTemplateCustomizer(final LoadBalancerInterceptor loadBalancerInterceptor) {
	return restTemplate -> {
		List<ClientHttpRequestInterceptor> list = new ArrayList<>(restTemplate.getInterceptors());
		list.add(loadBalancerInterceptor);
		restTemplate.setInterceptors(list);
	};
}
```

solution：
 

```

@Bean
    @ConditionalOnMissingBean
    public RestTemplateCustomizer restTemplateCustomizer(final LoadBalancerInterceptor loadBalancerInterceptor) {
        return restTemplate -> {
            List<ClientHttpRequestInterceptor> list = new ArrayList<>(restTemplate.getInterceptors());

            boolean isExists = false;

            for (ClientHttpRequestInterceptor clientHttpRequestInterceptor : list) {
                if(clientHttpRequestInterceptor instanceof LoadBalancerInterceptor){
                    isExists = true;
                }
            }

            if(!isExists){
                list.add(loadBalancerInterceptor);
                restTemplate.setInterceptors(list);
            }
        };
    }


```

**Comment by OlgaMaciaszek** [comment] 2022-12-22 12:29
Hello, @zhangle910522, that's most probably the case. However, in order to be able for us to verify it and debug it properly, can you please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue as a link to a small app or tests in GitHub, that can be cloned and run to verify the issue.

**Comment by spring-cloud-issues** [comment] 2022-12-29 12:31
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2023-01-05 12:31
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2023-01-05 12:31 UTC
Labels: waiting for feedback, feedback-reminder
