### ISSUE TITLE
Spring cloud loadbalancer without eureka server

### ISSUE THREAD

**Issue by anjanitsip** [spring-cloud/spring-cloud-commons#960] opened 2021-05-25 09:35 UTC
Spring Boot 2.2.3 with spring cloud load balancer. I am not able to run the application without a discovery server (Eureka) -

spring.cloud.discovery.enabled=false
spring.cloud.config.enabled=false
eureka.client.enabled=false

I am getting below exception

```
org.springframework.web.reactive.function.client.WebClientResponseException$ServiceUnavailable: 503 Service Unavailable from UNKNOWN
at org.springframework.web.reactive.function.client.WebClientResponseException.create(WebClientResponseException.java:207)
Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
|_ checkpoint ⇢ 503 from GET http://terminal-mgmt/terminal/aplinfo?aplName=jp
```

I have passed the server list as below

spring.cloud.discovery.client.simple.instances.my-service[0].uri = http:\my-service:port

**Comment by spencergibb** [comment] 2021-06-03 19:19
`terminal-mgmt != my-service`

**Comment by anjanitsip** [comment] 2021-06-04 01:57
my-service used as an example. In actual it is terminal-mgmt.

**Comment by spencergibb** [comment] 2021-06-04 02:02
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem?  It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2021-06-11 02:04
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-06-18 02:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-06-18 02:04 UTC
Labels: feedback-reminder, waiting for feedback
