### ISSUE TITLE
Default WebClient.Builder is LoadBalanced

### ISSUE THREAD

**Issue by michael-barker** [spring-cloud/spring-cloud-commons#387] opened 2018-07-03 12:22 UTC
This may have been the intended functionality but it threw me off at first from my previous experience with `RestTemplate`.  Since no default `RestTemplate` bean is provided it was always up to the app to provide one and mark it with `@LoadBalanced`.  The [documentation for a load balanced WebClient.Builder](http://cloud.spring.io/spring-cloud-static/Finchley.RELEASE/single/spring-cloud.html#_spring_webclient_as_a_load_balancer_client) has the `WebClient.Builder` being created as a bean and marked with `@LoadBalanced` as you would do for `RestTemplate`.  This isn't necessary since the default `WebClient.Builder` is already load balanced.

I expected the same behavior as `RestTemplate` where I would have to explicitly load balance a `WebClient.Builder` but received errors at runtime when trying to call a host that's not registered in service discovery.  Is this intentional since a default `WebClient.Builder` is provided unlike `RestTemplate`?  If intentional then maybe that could be made more obvious in the documentation.

edit:  I also noticed that WebClientCustomizers are applied differently depending on whether a WebClient.Builder is load balanced.  When registering your own non load balanced WebClient.Builder then no WebClientCustomizers are applied but for a load balanced WebClient.Builder then all WebClientCustomizer beans are applied in addition to the loadBalancedWebClientCustomizer.  Is this also intentional?

edit2:  When registering your own load balanced WebClient.Builder then it appears that where you inject it it matters whether you call build in the constructor or after startup.  If you call build in the constructor then you don't receive the loadBalancedWebClientCustomizer due to the ordering.

**Comment by ryanjbaxter** [comment] 2018-07-03 16:12
> This isn't necessary since the default WebClient.Builder is already load balanced.

There shouldnt be a `Webclient.Builder` bean unless you create it, can you provide details of the your project setup where you see this?  Or even better provide a sample that reproduces this?

**Comment by spencergibb** [comment] 2018-07-03 16:15
I believe spring boot creates one, but it shouldn't be load balanced by default. We may need to update the docs to put `@LoadBalanced` on the `@Autowired`.

**Comment by michael-barker** [comment] 2018-07-05 14:01
What about the inconsistency when registering a non load balanced vs load balanced where the customizers are applied to the load balanced version but not the non load balanced?  The ordering also matters depending on when you call build on the `WebClient.Builder`.  Should I create a separate issue(s) for that?

**Comment by ryanjbaxter** [comment] 2018-07-16 19:04
So I did some testing here.  Actually the `WebClient.Builder` bean created by Boot in `WebClientAutoConfiguration` DOES have the `LoadBalancerFilterExchangeFunction` applied to it as long as `ReactiveLoadBalancerAutoConfiguration` is on the classpath.  I am not sure how we could exclude our load balancer customizer from being initialized and used in this case unless we dont register the bean.

https://github.com/spring-projects/spring-boot/blob/v2.0.3.RELEASE/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/function/client/WebClientAutoConfiguration.java#L59

If you add the `@LoadBalanced` annotation to your `@Autowired` variable or to the injected parameter in your bean creation method AND you dont provide your own `@LoadBalanced` `WebClient.Builder` bean, you will get an error because the bean does not exist.

As soon as you provide your own `WebClient.Builder` bean the one from Boot is not created because it is `@ConditionalOnMissingBean`.

> The ordering also matters depending on when you call build on the WebClient.Builder
Yes this is true, `build` needs to be called at some point AFTER the customizers are added.    Funny enough Boot adds the customizers in the constructor of the configuration class, we wait until after all singleton beans are initialized before adding the load balanced customization.  @spencergibb I assume you had a reason for writing it this way, could you elaborate?

**Comment by elue** [comment] 2019-02-04 11:22
any update on this issue? It would be handy if we can configure this.

**Comment by ryanjbaxter** [comment] 2019-02-04 14:43
@elue what do you mean by "It would be handy if we can configure this."?

**Comment by spring-issuemaster** [comment] 2019-02-11 14:43
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-02-18 14:47
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by Anusien** [comment] 2019-04-25 16:16
@spencergibb did you ever look at @ryanjbaxter 's question?

I think the root of this issue is this: If you declare a @Bean of type WebClient.Builder and annotate it with @LoadBalanced, Spring Boot won't provide its prototype WebClient.Builder. So if any other thing needs either a WebClient.Builder or a WebClient, it will get the @LoadBalanced one (and not even a copy), even if you don't want it. The workaround would be to declare your own default @Scope("prototype") WebClient.Builder, but then you miss out on all the configuration from WebClientAutoConfiguration.

**Comment by elue** [comment] 2019-04-26 08:21
@ryanjbaxter , sorry for late feedback. you can refer to the description above provided by @Anusien .

**Comment by Anusien** [comment] 2019-05-16 16:54
For context, this is how we worked around it in a project I'm working on:

`    @Bean
    @Scope("prototype")
    @Primary
    public WebClient.Builder webClientBuilder(final ObjectProvider<WebClientCustomizer> customizerProvider) {
        final WebClient.Builder builder = WebClient.builder();
        customizerProvider.orderedStream().forEach((customizer) -> customizer.customize(builder));
        return builder;
    }`

**Comment by Anusien** [comment] 2019-08-30 19:51
Did the team ever get a chance to discuss this?

**Comment by ryanjbaxter** [comment] 2019-10-31 14:47
We have a very similar situation for `RestClientTeamplate` which we document
https://cloud.spring.io/spring-cloud-static/Greenwich.SR3/single/spring-cloud.html#_multiple_resttemplate_objects

I think we should also do the same for WebClient.Builder and include something like the code above which also configures all the `WebClientCustomizer`s.

**Closed** 2019-11-21 20:43 UTC
Labels: documentation
