### ISSUE TITLE
Error when using multiple spring profiles during bootstrap using @ActiveProfiles

### ISSUE THREAD

**Issue by deki** [spring-cloud/spring-cloud-commons#348] opened 2018-03-29 08:44 UTC
After updating a Spring Boot application from 1.5.x to 2.0.0.RELEASE along with Spring Cloud from Edgware to Finchley.M9, tests that contain multiple active profiles `@ActiveProfiles({"test", "gitlab-ci"})` no longer work and fail with

```
10:36:14.707 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: PropertySource named 'applicationConfig: [classpath:/bootstrap.yml] (document #1)' cannot be added relative to itself
	at org.springframework.core.env.MutablePropertySources.assertLegalRelativeAddition(MutablePropertySources.java:198)
	at org.springframework.core.env.MutablePropertySources.addAfter(MutablePropertySources.java:139)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.addLoadedPropertySources(ConfigFileApplicationListener.java:705)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:337)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:213)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:196)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:183)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:169)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:197)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:104)
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:70)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:74)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:351)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:317)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:138)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:107)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:242)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:227)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:289)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:291)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:246)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Looks like bootstrap.yml is added multiple times. It works if I only use a single profile.

**Comment by ryanjbaxter** [comment] 2018-04-02 11:05
Can you provide a sample that reproduces this?

**Comment by deki** [comment] 2018-04-05 06:38
Yes, I'll provide it next week.

**Comment by deki** [comment] 2018-04-06 18:37
Run `mvn clean install` in https://github.com/deki/spring-petclinic-microservices/tree/cloud-commons-issue-348/spring-petclinic-customers-service and you'll see the error.

**Comment by ryanjbaxter** [comment] 2018-04-11 15:20
Please provide a sample is minimally complex that reproduces the problem.

**Comment by deki** [comment] 2018-04-11 15:30
Well I thought taking the official cloud spring-petclinic should be easy to understand. Do you have a simpler one that I can fork?

Reproducing the error is as simple as my commit: https://github.com/deki/spring-petclinic-microservices/commit/f138fd37bbc5235e7134a97a38dd12548965f786

**Comment by ryanjbaxter** [comment] 2018-04-11 15:33
when I clone the app and run `mvn clean install` everything builds fine.  I noticed that it is not using boot 2.0 and finchley.m9 so if you want to try and correct it so i can reproduce the error without modifying the sample I can try again

**Comment by deki** [comment] 2018-04-11 15:39
Hmm are you sure you selected the cloud-commons-issue-348 branch?

**Comment by ryanjbaxter** [comment] 2018-04-12 18:10
Sorry I missed that part originally.  I am actually just able to reproduce this in an app that is far simpler.  It just has `spring-cloud-starter` on the classpath.  As soon as you activate more than one profile you see the problem.  It seems like in Boot 2.0.x `BootstrapApplicationListener` gets called twice, while in Boot 1.5.x it doesn't.  Seems like a new behavior.  @spencergibb @dsyer are you aware of any changes in this area?

**Comment by deki** [comment] 2018-05-03 14:35
Any update on this?

**Comment by ryanjbaxter** [comment] 2018-05-31 15:01
[demo.zip](https://github.com/spring-cloud/spring-cloud-commons/files/2058735/demo.zip)
Sample that reproduces the problem

**Comment by spencergibb** [comment] 2018-06-04 19:31
I don't see this while running a normal app with multiple profiles, correct?

**Comment by spencergibb** [comment] 2018-06-04 19:34
And only if `spring.profiles='test,another-test'` in application.properties.

**Comment by deki** [comment] 2018-06-04 19:46
Correct

**Comment by spencergibb** [comment] 2018-06-04 20:33
AFAIKT I can't see that spring cloud commons is doing anything incorrectly. The `BootstrapApplicationListener` getting called twice is a red herring. The error happens on the first call and three property sources with the same name (one for the null profile and one each for `test` and `another-test` are created. It fails on the attempt to add the 2nd after the first which has the same name.

@philwebb or @wilkinsona thoughts? Should I create a boot issue?

**Comment by philwebb** [comment] 2018-06-04 20:36
Possibly https://github.com/spring-projects/spring-boot/issues/13151. Would need to look in a bit more detail.

**Comment by spencergibb** [comment] 2018-06-04 20:38
No, I don't think so. It's because two property sources are created with the same name but reference the same profile in a yaml document

`applicationConfig: [classpath:/bootstrap.yml] (document #1)`

Because both `spring.profiles='test,another-test'` match document #1 and `ConfigFileApplicationListener.addLoadedPropertySources()` uses name to distinguish.

**Comment by spencergibb** [comment] 2018-06-04 20:41
Maybe two profiles matching the same yaml document should only produce one property source.

**Comment by spencergibb** [comment] 2018-06-04 20:56
In fact, the error is reproducible by removing spring cloud and moving to `application.yml`.

**Comment by spencergibb** [comment] 2018-06-04 21:01
Here is the updated project, no cloud. [demobootstrapmultiprofile.zip](https://github.com/spring-cloud/spring-cloud-commons/files/2069957/demobootstrapmultiprofile.zip)

**Comment by philwebb** [comment] 2018-06-04 22:30
This one is on use. I've raised https://github.com/spring-projects/spring-boot/issues/13362

**Comment by spencergibb** [comment] 2018-06-04 22:31
Closing in favor of boot issue

**Closed by spencergibb** 2018-06-04 22:31 UTC
Labels: bug
