### ISSUE TITLE
@RefreshScope on DataSource bean doesn't work with @Transactional

### ISSUE THREAD

**Issue by ivanhendrajaya** [spring-cloud/spring-cloud-commons#277] opened 2017-11-30 09:06 UTC
I am using Spring Boot 1.5.9.RELEASE and Spring Cloud Edgware.RELEASE.

### Sample Application
[https://github.com/ivanhendrajaya/spring/tree/master/spring-cloud-commons-gh-277](https://github.com/ivanhendrajaya/spring/tree/master/spring-cloud-commons-gh-277)

### Error
```
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:216) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:470) ~[spring-cloud-context-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.sun.proxy.$Proxy72.getTargetObject(Unknown Source) ~[na:na]
	at org.springframework.transaction.support.TransactionSynchronizationUtils$ScopedProxyUnwrapper.unwrapIfNecessary(TransactionSynchronizationUtils.java:185) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.support.TransactionSynchronizationUtils.unwrapResourceIfNecessary(TransactionSynchronizationUtils.java:70) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.support.TransactionSynchronizationManager.getResource(TransactionSynchronizationManager.java:137) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.orm.jpa.JpaTransactionManager.doGetTransaction(JpaTransactionManager.java:342) ~[spring-orm-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:337) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.createTransactionIfNecessary(TransactionAspectSupport.java:461) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:277) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96) ~[spring-tx-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673) ~[spring-aop-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.example.demo.DemoService$$EnhancerBySpringCGLIB$$ee1bcad4.findAll(<generated>) ~[main/:na]
	at com.example.demo.DemoController.findAll(DemoController.java:22) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_152]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_152]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_152]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_152]
```

**Comment by vakninr** [comment] 2017-12-27 14:56
Yep, got the same issue, run for me with Spring Boot 1.5.9 and Cloud Dalston version but not with Edgware

**Comment by sanderino666** [comment] 2018-01-09 14:04
I can confirm that this issue occurs after upgraded to Spring Boot 1.5.9 and Edgeware.RELEASE. Downgrading to Dalston.SR5 fixes the issue.

**Comment by Maarten-Damen** [comment] 2018-01-25 10:09
We also have this problem. We are planning to upgrade to spring-boot 2 with spring cloud Finchley. Does this problem also occur in Finchley? Are there plans to solve this or is there a work around?

**Comment by enriquerecarte** [comment] 2018-01-26 09:48
Hey, I just tried it with Spring Boot 2.0.0.M7 and Finchley.M5 and I have the same issue.

**Comment by sanderino666** [comment] 2018-02-01 21:25
@spencergibb is there by any chance a workaround available or can we help fixing this? We tried upgrading our codebase to Spring Boot 2 RC1 but Dalston.SR5 is not compatible with SB2 and we cannot move forward to Finchley due to this issue.

**Comment by spencergibb** [comment] 2018-02-02 00:10
Closed via cd436c7d1547f5f27d4b9a49f76a04b8aa83700b

**Closed by spencergibb** 2018-02-02 00:10 UTC
Labels: bug

**Comment by spencergibb** [comment] 2018-02-02 00:11
@sanderino666 @enriquerecarte @Maarten-Damen @vakninr @ivanhendrajaya can you try Edgware Snapshots?

**Comment by spencergibb** [comment] 2018-02-02 00:22
or Finchley snapshots if that is what you're using.

**Comment by sanderino666** [comment] 2018-02-03 11:34
@spencergibb I forked the sample project from @ivanhendrajaya, tested it against Edgware.BUILD-SNAPSHOT and it works as expected!

https://github.com/sanderino666/spring
