### ISSUE TITLE
config-client get error ipv6 config-server uri

### ISSUE THREAD

**Issue by huangleilz** [spring-cloud/spring-cloud-commons#558] opened 2019-04-26 07:08 UTC
config-client get invalid config server uri
when I test ipv6  get the config-server uri is http://fd15:4ba5:5a2b:1008:20c:29ff:fe7e:c316:8080 but the correct uri is http://[fd15:4ba5:5a2b:1008:20c:29ff:fe7e:c316]:8080

I fellow the code find this  
/**
	 * Creates a URI from the given ServiceInstance's host:port.
	 * @param instance the ServiceInstance.
	 * @return URI of the form (secure)?https:http + "host:port".
	 */
	public static URI getUri(ServiceInstance instance) {
		String scheme = (instance.isSecure()) ? "https" : "http";
		String uri = String.format("%s://%s:%s", scheme, instance.getHost(),
				instance.getPort());
		return URI.create(uri);
	}

so how can get right uri

**Comment by OlgaMaciaszek** [comment] 2022-06-13 14:43
@huangleilz @lyhu @vasureddys I have tweaked one of our samples to use an ipv6 host (https://github.com/OlgaMaciaszek/spring-cloud-intro-demo/compare/master...ipv6). Was not able to reproduce the issue on either Spring Cloud `2021.0.4-SNAPSHOT` or `2022.0.0-M2`. If the issue still persists for you on the current Spring Cloud versions, please 
 provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2022-06-20 14:44
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-06-27 14:44
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-06-27 14:44 UTC
Labels: feedback-reminder

**Comment by yoSoyCastorTroy** [comment] 2023-07-27 20:20
Hi @OlgaMaciaszek,
I Apologized in advance if I'm braking any rule by commenting on a closed ticket.

According to this post: _https://github.com/spring-cloud/spring-cloud-openfeign/issues/448#ref-issue-1431088875_
I see comments that says this issue is fixed with this commit _https://github.com/TencentBlueKing/bk-job/issues/1441_
Can you confirm if so?
Which release version has the fix?

I'll appreciate your inputs.
Best.

**Comment by OlgaMaciaszek** [comment] 2023-07-28 09:51
Hello @yoSoyCastorTroy I was not able to reproduce the issue on an upgraded version. If you're still facing the issue either on Spring Cloud `2021.0.8` or `2022.0.3`, please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.
