### ISSUE TITLE
Spring Boot Actuator endpoint /pause shuts Tomcat application server down

### ISSUE THREAD

**Issue by moritzluedtke** [spring-cloud/spring-cloud-commons#788] opened 2020-07-13 11:21 UTC
**Describe the bug**
We recently upgraded from spring boot `2.1.6.RELEASE` to `2.3.1.RELEASE`. After that we realized that the endpoint `/ops/pause` is not functioning any longer. Before it stopped two kafka consumers in our application. Now it seems to also shutdown the spring boot managed tomcat server. After the call we cannot get any requests working. The server refuses any connection after that but the application is still running (no exit codes in the log).

**Sample**
Don't have one right now but I can create a sample project if it helps.

**Workaround**
Revert back to `2.1.6.RELEASE` as we do not need any of the new features or bug fixes.

**More info**
- Java 11
- Spring Boot 2.3.1.RELEASE

Management related properties in our application.properties:
```
management.health.status.order=DOWN, UP
management.endpoint.jolokia.enabled=true
management.endpoint.metrics.enabled=true
management.endpoint.pause.enabled=true
management.endpoint.resume.enabled=true
management.endpoint.restart.enabled=true

management.endpoints.web.exposure.include=*
management.endpoints.web.base-path=/ops
```

The log after calling `/ops/pause`:
```
2020-07-13 11:55:15,347 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.coyote.http11.Http11NioProtocol - Pausing ProtocolHandler ["http-nio-31016"]
2020-07-13 11:55:15,355 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.catalina.core.StandardService - Stopping service [Tomcat]
2020-07-13 11:55:15,357 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.catalina.core.StandardWrapper - Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2020-07-13 11:55:16,363 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.catalina.core.StandardWrapper - Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2020-07-13 11:55:17,389 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.catalina.core.StandardWrapper - Waiting for [1] instance(s) to be deallocated for Servlet [dispatcherServlet]
2020-07-13 11:55:17,493 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Destroying Spring FrameworkServlet 'dispatcherServlet'
2020-07-13 11:55:17,500 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.coyote.http11.Http11NioProtocol - Stopping ProtocolHandler ["http-nio-31016"]
2020-07-13 11:55:17,503 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 WARN  o.apache.tomcat.util.net.NioEndpoint - The executor associated with thread pool [http-nio-31016] has not fully shutdown. Some application threads may still be running.
2020-07-13 11:55:17,504 [http-nio-31016-exec-2] traceId=3b2fc7d64f4e0d82 spanId=3b2fc7d64f4e0d82 INFO  o.a.coyote.http11.Http11NioProtocol - Destroying ProtocolHandler ["http-nio-31016"]
2020-07-13 11:55:17,542 [http-nio-31016-exec-2] traceId= spanId= ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
java.lang.NullPointerException: null
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at io.micrometer.core.instrument.ImmutableTag.<init>(ImmutableTag.java:35)
	at io.micrometer.core.instrument.Tag.of(Tag.java:29)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcTags.method(WebMvcTags.java:74)
	at org.springframework.boot.actuate.metrics.web.servlet.DefaultWebMvcTagsProvider.getTags(DefaultWebMvcTagsProvider.java:74)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.getTimer(WebMvcMetricsFilter.java:169)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.record(WebMvcMetricsFilter.java:129)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-13 11:55:17,546 [http-nio-31016-exec-2] traceId= spanId= ERROR o.a.coyote.http11.Http11Processor - Error processing request
java.lang.NullPointerException: null
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:412)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-07-13 11:55:17,547 [http-nio-31016-exec-2] traceId= spanId= WARN  o.a.catalina.connector.CoyoteAdapter - Exception while attempting to add an entry to the access log
java.lang.NullPointerException: null
	at org.apache.catalina.connector.CoyoteAdapter.log(CoyoteAdapter.java:490)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:403)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)

```

**Comment by moritzluedtke** [comment] 2020-07-13 11:33
A colleague of mine found out that in the class DefaultLifecycleProcessor all beans are collected which will be shut down. If you call the mentioned actuator endpoint the list of beans is the following for us:
- documentationPluginsBootstrapper
- org.springframework.kafka.config.internalKafkaListenerEndpointRegistry
- webServerGracefulShutdown
- webServerStartStop

**Comment by ryanjbaxter** [comment] 2020-07-13 14:16
Would you mind creating a sample app so we can take a look?

**Comment by moritzluedtke** [comment] 2020-07-14 11:32
Sure, no problem:
https://github.com/moritzluedtke/spring-actuator-problem

I could not reproduce the NPE. We assume that the service wanted to write something to the logs but the tomcat was already in shut down mode and the log was no longer available.
But you can see how the `/pause` command takes down the tomcat and the application.

We also did a bunch of testing and found out that this started to happen with spring boot version `2.3.0.RELEASE`. The spring-cloud-dependencies did not seem to affect this issue as it appears in both `Greenwich.SR2` and `Hoxton.SR6`

**Comment by moritzluedtke** [comment] 2020-07-28 07:37
Did anyone had a chance to take a look at this?

**Comment by moritzluedtke** [comment] 2020-08-10 08:49
This behaviour is still present in spring-boot `2.3.2`.

**Comment by olagache** [comment] 2020-08-26 12:43
Same issue for me.
Calling `/actuator/pause` return no awswer. Connection is closed before ...

```
curl -i -X POST    -H "Authorization:Bearer xxxxxxx"  'http://localhost:48880/secure/pause'
--> curl: (52) Empty reply from server
```
Unable to call `resume` ,`info` or `health` after pause
```
curl -i -X POST    -H "Authorization:Bearer xxxxxxx"  'http://localhost:48880/secure/resume'
--> curl: (7) Failed to connect to localhost port 48880: Connexion refusée
```
In `discovery` application the paused service is marked as down and the `PID` (`with ps command`) is present.

**Comment by olagache** [comment] 2020-09-08 11:16
@moritzluedtke : No news ?

**Comment by moritzluedtke** [comment] 2020-09-14 14:51
Hey @olagache,

I'm only the reporter of this issue. I am not involved in the development of the spring framework or it's dependent projects.

So I guess we have to wait for an answer from the devs of this project.

**Comment by spencergibb** [comment] 2020-09-14 14:56
Pause simple calls `this.context.stop()` where `context` is the spring application context. Boot may have changed things enough that pause no longer works. @dsyer thoughts?

**Comment by spencergibb** [comment] 2020-10-01 14:51
Looks like we need to have a broader conversation with the boot team. @philwebb did graceful shutdown change the behavior of servlet containers to use lifecycle methods to shut down? There are use cases where stopping the context is valid while keeping the app up. /cc @garyrussell @olegz

**Comment by wilkinsona** [comment] 2020-10-01 16:08
> Did graceful shutdown change the behavior of servlet containers to use lifecycle methods to shut down

Yes, the change to integrate with the context lifecycle was made based on user feedback on 2.3 RC1. See https://github.com/spring-projects/spring-boot/issues/21325 for some details.

**Comment by mk352** [comment] 2020-11-10 22:22
Any updates on this from the Spring Boot team? This change is causing our deployment flow to fail since we rely on the endpoints to pause the application and allow to drain prior to deployment.

**Comment by wilkinsona** [comment] 2020-11-11 07:14
@mk352, I'm a member of the Boot team.

**Comment by mk352** [comment] 2020-11-11 14:55
@wilkinsona Was this implemented by design or is this a bug? I'm currently using V2.3.2 and wondering if I should revert until this is resolved.

**Comment by wilkinsona** [comment] 2020-11-11 15:24
It is by design. As I said above, the change was made following user feedback on 2.3 RC1. Basing graceful shutdown on the application context's lifecycle allows other components to participate in the shutdown, something which was not possible previously.

I'd argue that it's correct that the application should stop accepting requests when it has been paused. IMO, the problem is really that pause either results in the application exiting (if there are no non-daemon threads left running) or not being able to make a resume request over HTTP. It may be possible to circumvent the latter by using JMX.

**Comment by garyrussell** [comment] 2020-11-11 17:34
>Pause simpl[y] calls this.context.stop()

That doesn't seem right to me; pause is a first class concept for Kafka consumers - keep the consumer alive but don't consume any records.

Containers for `@KafkaListener`s can be paused/resumed using the `KafkaListenerEndpointRegistry`.

```java
this.listenerRegistry.getListenerContainers().forEach(cont -> cont.pause());
```

Spring Integration components implement `Pausable` which is a sub-interface of `LifeCycle`.

Spring Cloud Stream has an endpoint for pausing/resuming consumer bindings.

**Comment by dsyer** [comment] 2020-11-12 08:53
Seems like we need to fix this endpoint in Spring Cloud Commons. It probably should have an extension point that can be implemented for the various flavours above and dropped into conditional autoconfigurations. Spring Cloud Stream shouldn't (IMO) have its own endpoint for this, since the whole reason for the Commons one to exist was to provide that functionality, so it should probably deprecate it and provide some autoconfiguration for the hook that we provide. Or maybe it wouldn't need to if all it is doing is calling `Pausable.pause()` because that's generic enough that Commons can do it (at the expense of one more optional dependency).

**Comment by moritzluedtke** [comment] 2020-11-12 09:42
I agree that a paused application should not accept requests but I disagree that it should be completely shut down. That is not something I would expect from the word `pause`.

As @garyrussell already said this is used with Kafka and that is the way we use it in our deployment pipelines, too.
Pause the consumers, so that every message was consumed normally and nothing gets lost. Then kill the application and deploy a new one.

**Comment by wilkinsona** [comment] 2020-11-12 10:01
>  but I disagree that it should be completely shut down

I don't think anyone's arguing that's what should happen. The current implementation relies upon the web container's request-handling threads to keep the JVM alive during the pause. If it wants to be certain that the JVM will remain alive while everything has been paused, it needs to ensure that a non-daemon thread that it controls is alive for the duration of the pause.

**Comment by dsyer** [comment] 2020-11-12 10:14
If you want to "kill the application and deploy a new one" @moritzluedtke then I would argue that `/shutdown` *is* the correct endpoint. The current behaviour of `/pause` is wrong (in fact it has always been wrong, but this new graceful sutdown feature in Boot has only just now made us notice), so the idea is to fix it.

**Closed** 2020-12-01 09:34 UTC
Labels: bug
