### ISSUE TITLE
can't read log4j2-dev.xml or logback-dev.xml

### ISSUE THREAD

**Issue by liuxinglanyue** [spring-cloud/spring-cloud-commons#166] opened 2017-01-09 03:53 UTC
application.properties
`spring.profiles.active=dev`

application-dev.properties
`logging.config=classpath:log4j2-dev.xml`

BootstrapApplicationListener  only read bootstrap.properties

but evn is  spring.cloud.bootstrap.name=application  OK

**Comment by spencergibb** [comment] 2017-01-09 20:11
You can't given much detail on what is going on. Can you elaborate more on what the problem is and what you are trying to accomplish?

**Comment by liuxinglanyue** [comment] 2017-01-10 02:40
application.properties
`spring.profiles.active=dev`

application-dev.properties
`logging.config=classpath:log4j2-dev.xml`

unused spring-cloud ,  log4j2-dev.xml  is  effective
use spring-cloud , log4j2-dev.xml is noneffective

but evn is spring.cloud.bootstrap.name=application OK

**Comment by spencergibb** [comment] 2017-01-10 03:05
thats the same thing you said before.

**Comment by spencergibb** [comment] 2017-04-04 03:00
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2017-04-04 03:00 UTC
Labels: waiting for feedback
