### ISSUE TITLE
SpringCloud LoadBalancer not support Retry, we want Retry Instance exclude not exist in Eureka .

### ISSUE THREAD

**Issue by BrandNewMe402** [spring-cloud/spring-cloud-commons#984] opened 2021-07-20 07:50 UTC
![image](https://user-images.githubusercontent.com/43813184/126282154-acd805df-3896-43ea-a469-67de88e50136.png)

![image](https://user-images.githubusercontent.com/43813184/126282586-7ba840b9-9c97-4b17-94ce-ffd58185c51f.png)

what can i do ? Let LoadBalancer's Retry effective?

**Comment by OlgaMaciaszek** [comment] 2021-07-27 11:07
@BrandNewMe402  Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue.

**Comment by spring-cloud-issues** [comment] 2021-08-03 11:08
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-08-10 11:08
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-08-10 11:08 UTC
Labels: waiting for feedback, feedback-reminder
