### ISSUE TITLE
Healthcheck failure on RefreshScope

### ISSUE THREAD

**Issue by lechen26** [spring-cloud/spring-cloud-commons#943] opened 2021-04-07 20:16 UTC
Hi

i have a spring boot app (2.2.7.RELEASE) with Spring cloud (Hoxton.SR6) and i have an issue with Cronjob on K8s and i wonder if its a bug or misconfiguration from our side.

sometimes when the spring application finishing the work and status changed to DOWN we get the additional error of healthcheck failure which seems to be related to refreshScope operation.

```
Saw local status change event StatusChangeEvent [timestamp=1617818479572, current=DOWN, previous=UP]
Saw local status change event StatusChangeEvent [timestamp=1617818479586, current=OUT_OF_SERVICE, previous=DOWN]
hutting down DiscoveryClient ...
DataSource health check failed org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLException: HikariDataSource HikariDataSource (Hikari) has been closed. at
Health check failed org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'refreshScope': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!
DiscoveryClient_MYJOB/MyJob:73ddcf20013a9695468c8e436e5a0620: registering service...
DiscoveryClient_MYJOB/MyJob:73ddcf20013a9695468c8e436e5a0620 - registration status: 204
Completed shut down of DiscoveryClient
```

i understand the app is in the process of shutdown. 
the reason for these errors is that once the app understatnd its about to get down tthere is an operation of refresh and sometimes once this Refresh operation happens when the DB connection already close we get this error?

should we configure  spring.cloud.refresh.extra-refreshable: com.zaxxer.hikari.HikariDataSource ?

thanks

CL

**Comment by ryanjbaxter** [comment] 2021-04-08 14:01
If the app is already being shut down how much does the error really matter?

There are some things in Spring Boot 2.4.x that might help
https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/html/spring-boot-features.html#boot-features-graceful-shutdown

**Comment by lechen26** [comment] 2021-04-11 07:00
the error itself does not 'alert' us , its just pretty annoying w get this from all of our services.
we monitor our errors and being notified on them. i cant really just exclude them as the same error can indicate a real issue.

i'm not quite sure gracefully shutdown will help here, and the thing i;m trying to understand here is, why during shutdown of the app the healthcheck aggregator take place and check all health check?
does it make sense?

10x

**Comment by ryanjbaxter** [comment] 2021-04-15 17:50
I am wondering if the health check is being performed because you are using the `/health` endpoint for the liveliness check in Kubernetes?  In which case and HTTP request is being made and the graceful shutdown configuration could help.

Did you try setting `spring.cloud.refresh.extra-refreshable: com.zaxxer.hikari.HikariDataSource`?

**Comment by spring-cloud-issues** [comment] 2021-04-22 17:52
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-04-29 17:52
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-04-29 17:52 UTC
Labels: feedback-reminder, waiting for feedback

**Comment by bhavesh-dhera** [comment] 2021-11-02 15:40
Facing the same issue, has there been any update here @ryanjbaxter @lechen26 ?

**Comment by ryanjbaxter** [comment] 2021-11-02 18:38
Please try 2021.0.4 and if you are still having issues please provide a sample to reproduce the problem

**Comment by bhavesh-dhera** [comment] 2021-11-10 10:39
But I am on Spring Boot 2.2.x(incompatible with latest versions of cloud). Is there any other Hoxton version that fixes this?

**Comment by ryanjbaxter** [comment] 2021-11-10 12:37
Spring Boot 2.2.x is end of life and no longer supported, I suggest you upgrade 

https://github.com/spring-projects/spring-boot/wiki/Supported-Versions
