### ISSUE TITLE
Decryption, config server, and profile order

### ISSUE THREAD

**Issue by bakslashr** [spring-cloud/spring-cloud-commons#580] opened 2019-07-12 16:35 UTC
Spring Cloud: Greenwich.SR1

Setup: Using the config server, we have two profiles p1 and p2. Each of these profiles have an encrypted value with the same name "myencryptedvalue". When the active profiles are specified in the order of p1 and p2, the spring environment returns the last value defined in the last profile, p2.

Expected: When using the decryption, the values that are returned should be those that are naturally returned via the spring environment.

Actual: It decrypts p2 first, and then decrypts p1, which overwrites the p2 value. (for us, p1 actually fails, but failures are ignore and it replaces p2 with a blank string)

Note: When using no config server, and using just resources `EnvironmentDecryptApplicationInitializer` does the right thing and reverses through the PropertySources list.

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L168

However, it does not do the same for `CompositePropertySource`
To be consistent it seems that it should also do these in reverse order.

https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/encrypt/EnvironmentDecryptApplicationInitializer.java#L186

**Comment by TYsewyn** [comment] 2019-07-16 18:22
Duplicate of #475 and is fixed with #581.

**Closed** 2019-07-18 14:54 UTC
Labels: duplicate, waiting-for-triage
