### ISSUE TITLE
Coerce false to OFF in LoggingRebinder

### ISSUE THREAD

**Issue by lkwg82** [spring-cloud/spring-cloud-commons#556] opened 2019-04-23 09:34 UTC
Bug report

I try to keep logger in  a sub library deactivated in `application.yml` with 

```
logging:
  level:
    com.oembedler.moon.graphql.boot.error.GraphQLErrorHandlerFactory: OFF
```
this works until I add to my `pom.xml`

```
      <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
        </dependency>
```
It tells me 
```
ERROR LoggingRebinder [main] [] - Cannot set level: false for 'com.oembedler.moon.graphql.boot.error.GraphQLErrorHandlerFactory'
```

It seems like the `LoggingRebinder` do not accept `OFF` as a value and fallback to `false`.
This breaks the configuration at this point. (The logger keeps unconfigured.)

Enhancement

Currently I don't know if this is missing or intended. 

Thx for helping!

**Comment by OlgaMaciaszek** [comment] 2019-05-07 18:29
Hello @lkwg82 Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. Will have a look at the issue then.

**Comment by spring-issuemaster** [comment] 2019-05-15 12:38
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by lkwg82** [comment] 2019-05-17 09:15
see https://github.com/lkwg82/spring-cloud-commons-556

pls configure a config server to trigger this https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-context/src/main/java/org/springframework/cloud/bootstrap/config/PropertySourceBootstrapConfiguration.java#L105

to get into the critical execution path

Maybe you know better to mock that.

Hope it helps.

**Comment by OlgaMaciaszek** [comment] 2019-06-28 13:54
Hello @lkwg82 I was able to reproduce it. This, in fact, happens, but is not a cloud issue, so I will be closing this. 

The underlying reason for that is that Spring Boot uses SnakeYaml, that implements YAML 1.1, where `OFF` is resolved to a `boolean` `false` (https://yaml.org/type/bool.html). 

As a workaround, you can put just this one property in a .properties file.

**Comment by wilkinsona** [comment] 2019-06-28 16:35
As an alternative to using a properties file, you can quote the value to prevent it being coerced to a boolean:

```yaml
logging:
  level:
    com.oembedler.moon.graphql.boot.error.GraphQLErrorHandlerFactory: "OFF"
```

**Comment by wilkinsona** [comment] 2019-06-28 16:38
Spring Cloud could also consider coercing `false` to `OFF` as Boot does since https://github.com/spring-projects/spring-boot/issues/3628.

**Comment by spencergibb** [comment] 2019-06-28 16:49
Let's follow what boot does.

**Comment by lkwg82** [comment] 2019-06-28 18:35
Thx for this high quality answer!

**Closed** 2019-07-01 12:16 UTC
Labels: enhancement, help wanted
