### ISSUE TITLE
Get spring cloud version

### ISSUE THREAD

**Issue by SoftwareKing** [spring-cloud/spring-cloud-commons#489] opened 2019-03-10 07:51 UTC
I want to get spring cloud version, how to get it? get spring boot version,as follows

```java
SpringBootVersion.getVersion();
```
I want to get spring cloud version,Is there any way?

**Comment by shakuzen** [comment] 2019-03-11 06:49
Duplicate of #421

**Comment by SoftwareKing** [comment] 2019-03-11 07:27
Duplicate of #421，Repeat for a long time, when to support？@shakuzen @royclarkson

**Closed** 2019-03-11 14:20 UTC
Labels: duplicate

**Comment by SoftwareKing** [comment] 2019-03-12 05:50
Close directly? When will it be settled? @ryanjbaxter

**Comment by spencergibb** [comment] 2019-03-12 05:53
Please follow #421. It is not scheduled.
