### ISSUE TITLE
Unable to override local configurations using -Dspring.profiles.active=pre on SpringCloud version 2021.0.8.

### ISSUE THREAD

**Issue by Iamdouding** [spring-cloud/spring-cloud-commons#1317] opened 2023-12-27 09:36 UTC
spring-cloud-dependencies  version 2021.0.8.   

Problem Description：
I specified the Spring configuration in bootstrap.yml as follows:

```yaml
spring:
  profiles:
    active: dev
```    

 At the same time, I overrode it during startup using -Dspring.profiles.active=pre. However, when using the Spring Cloud Dependencies version 2021.0.8, the active profile is not overridden correctly. Instead, it outputs the following information: "The following 2 profiles are active: "pre", "dev".

springBoot version is 2.6.15

**Comment by ryanjbaxter** [comment] 2023-12-27 13:57
Can you try Spring Cloud 2022.0.4 and see if there is the same behavior?

**Comment by Iamdouding** [comment] 2023-12-28 06:28
I did not use the 2022.0.4 version, but trying with version 2021.0.7 worked. My solution was to change the configuration from:
```yaml
spring:
  profiles:
    active: dev
```    
to:
```yaml
spring:
  profiles:
    default: dev
```

**Comment by OlgaMaciaszek** [comment] 2024-01-11 10:37
Hello, @Iamdouding, as you can see in the[ project maintenance site](https://spring.io/projects/spring-cloud-commons/#support), the only version currently in OSS support is `4.1.x` (`2023.0.x` release train).  Please let us know if the issue is  still present on `2023.0.0`.

**Comment by spring-cloud-issues** [comment] 2024-01-18 10:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2024-01-25 10:37
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2024-01-25 10:37 UTC
Labels: feedback-reminder
