### ISSUE TITLE
LoadBalancerUriTools does not take into account server.servlet.context-path

### ISSUE THREAD

**Issue by DemianTinkiel** [spring-cloud/spring-cloud-commons#1118] opened 2022-06-06 16:27 UTC
**Describe the bug**
When `LoadBalancerUriTools#reconstructURI` is called  it does not take into account `server.servlet.context-path`. As a result anything trying to resolve the URL will point to something like `localhost:8080` instead of `localhost:8080/api` and fail to call APIs on the target.

I discovered this while looking at the example in [feign-eureka](https://github.com/spring-cloud-samples/feign-eureka)

**Sample**
1.get  [feign-eureka](https://github.com/spring-cloud-samples/feign-eureka)
2. add `server.servlet.context-path=/api` to `src/main/resources/application.yml`
3. run example
4. server will listen in `localhost:8080/api/` and client will request `localhost:8080/` resulting in 404

**Comment by OlgaMaciaszek** [comment] 2022-06-10 09:01
Hello, @DemianTinkiel . Seems to be a duplicate of [this issue](https://github.com/spring-cloud/spring-cloud-commons/issues/843). Please refer to it to see the discussion and decision log on this feature.

**Closed by OlgaMaciaszek** 2022-06-10 09:01 UTC
Labels: duplicate
